# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestUntitled():
  def setup_method(self, method):
    self.driver = webdriver.Remote(command_executor='http://localhost:4444/wd/hub', desired_capabilities=DesiredCapabilities.CHROME)
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_untitled(self):
    self.driver.get("https://colab.research.google.com/notebooks/welcome.ipynb?hl=ja")
    self.driver.set_window_size(784, 824)
    self.driver.find_element(By.LINK_TEXT, "ログイン").click()
    self.driver.find_element(By.ID, "identifierId").click()
    self.driver.find_element(By.ID, "identifierId").send_keys("aoitane333@gmail.com")
    self.driver.find_element(By.CSS_SELECTOR, ".RveJvd").click()
    self.driver.find_element(By.NAME, "password").click()
    self.driver.find_element(By.NAME, "password").send_keys("Kaminari1123")
    self.driver.find_element(By.CSS_SELECTOR, "#passwordNext .RveJvd").click()
    self.driver.find_element(By.CSS_SELECTOR, "#file-menu-button .goog-menu-button-caption").click()
    self.driver.find_element(By.CSS_SELECTOR, "#\\3A 5 > .goog-menuitem-content").click()
    element = self.driver.find_element(By.LINK_TEXT, "Colaboratory の概要")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).perform()
    element = self.driver.find_element(By.CSS_SELECTOR, "body")
    actions = ActionChains(self.driver)
    actions.move_to_element(element, 0, 0).perform()
    self.driver.find_element(By.CSS_SELECTOR, ".dialog-table-item:nth-child(3) .row-link-text").click()
    self.driver.execute_script("window.scrollTo(0,0)")
    self.driver.find_element(By.CSS_SELECTOR, "#cell-TPrgVOksahuN > .main-content #icon").click()
    self.driver.execute_script("window.scrollTo(0,0)")
  
